### ISSUE TITLE
sqlite error sqlite3_prepare failed: near "("  by openvasmd7.0.2

### ISSUE THREAD

**Issue by wrenchonline** [greenbone/gvmd#552] opened 2019-05-22 08:49 UTC
d manage:WARNING:2019-05-22 08h30.58 UTC:18958: sql_prepare_internal: sqlite3_prepare failed: near "(": syntax error sql:SELECT * FROM (WITH users_with_access ("user") AS (VALUES (1))  SELECT DISTINCT min_qod, override, "user"  FROM report_counts  WHERE report = 37    AND "user" IN (SELECT "user"                     FROM users_with_access)    AND min_qod <= 2147483647  UNION SELECT 0 as min_qod, 0, "user"          FROM users_with_access  UNION SELECT 0 as min_qod, 1, "user"          FROM users_with_access  UNION SELECT 70 as min_qod, 0, "user"          FROM users_with_access  UNION SELECT 70 as min_qod, 1, "user"          FROM users_with_access) AS inner_query ORDER BY "user"
but i using sqlite3 ,it is sucess, :
[root@localhost build]# sqlite3 /usr/local/var/lib/openvas/mgr/tasks.db
SQLite version 3.28.0 2019-04-16 19:49:53
Enter ".help" for usage hints.
sqlite> SELECT * FROM (WITH users_with_access ("user") AS (VALUES (1))  SELECT DISTINCT min_qod, override, "user"  FROM report_counts  WHERE report = 37    AND "user" IN (SELECT "user"                     FROM users_with_access)    AND min_qod <= 2147483647  UNION SELECT 0 as min_qod, 0, "user"          FROM users_with_access  UNION SELECT 0 as min_qod, 1, "user"          FROM users_with_access  UNION SELECT 70 as min_qod, 0, "user"          FROM users_with_access  UNION SELECT 70 as min_qod, 1, "user"          FROM users_with_access) AS inner_query ORDER BY "user"
   ...> 
   ...> ;
0|0|1
0|1|1
70|0|1
70|1|1
sqlite> 
I don't know why

**Comment by cfi-gb** [comment] 2019-05-22 08:58
Closing as a duplicate of https://github.com/greenbone/gvmd/issues/17

Your current openvas-manager installation is build against an outdated sqlite library version (not to be mixed with the version of the sqlite3 binary shown in the output) not matching the following requirements:

https://github.com/greenbone/gvmd/blob/d85cd7673cd0d87b76e01bcea1db02a66d39fdf8/INSTALL#L17 (added in https://github.com/greenbone/gvmd/pull/465).

**Closed by cfi-gb** 2019-05-22 08:58 UTC
