### ISSUE TITLE
gvmd-9.0.0: unable to finish the update, cpu 100%

### ISSUE THREAD

**Issue by blshkv** [greenbone/gvmd#822] opened 2019-10-19 11:25 UTC
```ps ax``` shows ```gvmd: Syncing SCAP```
here is the full a log file:
https://gist.github.com/blshkv/7ee3e3db3fff9307836a15988b1cc355

**Comment by tgurr** [comment] 2019-10-22 07:25
I think I'm experiencing the same issue, in my case you can also see postgresql working via ps ax like `postgres: gvm gvmd [local] SELECT` and hogging one of the CPUs with 100% and in `/var/log/gvm/gvmd.log` that it's actually doing something, from time to time:

```
md manage:   INFO:2019-10-21 14h23.03 utc:983: Updating /var/lib/gvm/scap-data/nvdcve-2.0-2008.xml
md manage:   INFO:2019-10-21 14h26.18 utc:983: Updating /var/lib/gvm/scap-data/nvdcve-2.0-2009.xml
md manage:   INFO:2019-10-21 14h33.58 utc:983: Updating /var/lib/gvm/scap-data/nvdcve-2.0-2019.xml
md manage:   INFO:2019-10-21 15h07.07 utc:983: Updating /var/lib/gvm/scap-data/nvdcve-2.0-2011.xml
md manage:   INFO:2019-10-21 19h00.46 utc:983: Updating /var/lib/gvm/scap-data/nvdcve-2.0-2014.xml
md manage:   INFO:2019-10-21 19h39.52 utc:983: Updating /var/lib/gvm/scap-data/nvdcve-2.0-2013.xml
md manage:   INFO:2019-10-21 19h41.55 utc:983: Updating /var/lib/gvm/scap-data/nvdcve-2.0-2015.xml
md manage:   INFO:2019-10-21 20h59.57 utc:983: Updating /var/lib/gvm/scap-data/nvdcve-2.0-2016.xml
md manage:   INFO:2019-10-22 04h11.11 utc:983: Updating /var/lib/gvm/scap-data/nvdcve-2.0-2005.xml
md manage:   INFO:2019-10-22 04h12.33 utc:983: Updating /var/lib/gvm/scap-data/nvdcve-2.0-2007.xml
md manage:   INFO:2019-10-22 04h17.30 utc:983: Updating /var/lib/gvm/scap-data/nvdcve-2.0-2002.xml
md manage:   INFO:2019-10-22 04h18.25 utc:983: Updating /var/lib/gvm/scap-data/nvdcve-2.0-2012.xml
md manage:   INFO:2019-10-22 04h49.50 utc:983: Updating /var/lib/gvm/scap-data/nvdcve-2.0-2017.xml
md manage:   INFO:2019-10-22 06h22.24 utc:983: Updating /var/lib/gvm/scap-data/nvdcve-2.0-2006.xml
md manage:   INFO:2019-10-22 06h23.57 utc:983: Updating /var/lib/gvm/scap-data/nvdcve-2.0-2004.xml
md manage:   INFO:2019-10-22 06h24.35 utc:983: Updating /var/lib/gvm/scap-data/nvdcve-2.0-2003.xml
md manage:   INFO:2019-10-22 06h25.51 utc:983: Updating /var/lib/gvm/scap-data/nvdcve-2.0-2010.xml
md manage:   INFO:2019-10-22 06h55.15 utc:983: Updating /var/lib/gvm/scap-data/nvdcve-2.0-2018.xml
```
as you can see on the timestamps it's taking **ages** (and even now still running). It never took **this** long with sqlite in previous versions. Running PostgreSQL 11.5.

**Comment by TheDoctor0** [comment] 2019-10-23 11:43
I can confirm that the problem really exists in the newest version of GVM.
It takes a few minutes at most to sync CERT data, but SCAP syncing is a never-ending story with 100% CPU load - I gave up after 7 hours.

**Comment by bjoernricks** [comment] 2019-10-23 12:22
Just to let you know. We are aware of this issue but we don't have a ETA for the fix yet.

**Comment by blshkv** [comment] 2019-10-25 14:15
This is not cool. You have released a buggy version. Please fix it ASAP.

**Comment by peacepenguin** [comment] 2019-11-07 20:48
I'm also stuck in "gvmd: Syncing SCAP" using gvmd-9.0.0. About 24 hours later it appears to be almost done 😅 .

I also noticed this bug when using PostgreSQL with GVM-10 a few weeks ago when installing from a PPA in ubuntu. I wanted to prepare my install methods to use postgresql instaed of sqllite. But when the cpu went high for so long, i assumed the PPA wasn't maintained correctly so i tried compiling from source, saw that GVM11 is released, so switched over to compile that version. Which worked, but I still see this high CPU bug.


```
md manage:   INFO:2019-11-06 21h38.40 utc:1766: Updating /opt/install/gvm11/var/lib/gvm/scap-data/nvdcve-2.0-2006.xml
md manage:   INFO:2019-11-06 21h40.20 utc:1766: Updating /opt/install/gvm11/var/lib/gvm/scap-data/nvdcve-2.0-2014.xml
md manage:   INFO:2019-11-06 22h27.53 utc:1766: Updating /opt/install/gvm11/var/lib/gvm/scap-data/nvdcve-2.0-2012.xml
md manage:   INFO:2019-11-06 23h05.05 utc:1766: Updating /opt/install/gvm11/var/lib/gvm/scap-data/nvdcve-2.0-2016.xml
md manage:   INFO:2019-11-07 08h17.45 utc:1766: Updating /opt/install/gvm11/var/lib/gvm/scap-data/nvdcve-2.0-2019.xml
md manage:   INFO:2019-11-07 09h06.34 utc:1766: Updating /opt/install/gvm11/var/lib/gvm/scap-data/nvdcve-2.0-2013.xml
md manage:   INFO:2019-11-07 10h11.00 utc:1766: Updating /opt/install/gvm11/var/lib/gvm/scap-data/nvdcve-2.0-2003.xml
md manage:   INFO:2019-11-07 10h12.35 utc:1766: Updating /opt/install/gvm11/var/lib/gvm/scap-data/nvdcve-2.0-2009.xml
md manage:   INFO:2019-11-07 10h23.44 utc:1766: Updating /opt/install/gvm11/var/lib/gvm/scap-data/nvdcve-2.0-2011.xml
md manage:   INFO:2019-11-07 15h16.35 utc:1766: Updating /opt/install/gvm11/var/lib/gvm/scap-data/nvdcve-2.0-2015.xml
md manage:   INFO:2019-11-07 16h58.26 utc:1766: Updating /opt/install/gvm11/var/lib/gvm/scap-data/nvdcve-2.0-2010.xml
md manage:   INFO:2019-11-07 17h34.45 utc:1766: Updating /opt/install/gvm11/var/lib/gvm/scap-data/nvdcve-2.0-2004.xml
md manage:   INFO:2019-11-07 17h36.00 utc:1766: Updating /opt/install/gvm11/var/lib/gvm/scap-data/nvdcve-2.0-2005.xml
md manage:   INFO:2019-11-07 17h38.10 utc:1766: Updating /opt/install/gvm11/var/lib/gvm/scap-data/nvdcve-2.0-2007.xml
md manage:   INFO:2019-11-07 17h44.42 utc:1766: Updating /opt/install/gvm11/var/lib/gvm/scap-data/nvdcve-2.0-2018.xml
md manage:   INFO:2019-11-07 19h06.36 utc:1766: Updating /opt/install/gvm11/var/lib/gvm/scap-data/nvdcve-2.0-2017.xml

```

**Comment by bjoernricks** [comment] 2019-11-08 09:35
Hi,

> This is not cool. You have released a buggy version. Please fix it ASAP.

the issue should be fixed with the current feed. Please be aware that an initial feed update still may take more then an hour but it shouldn't take days anymore.

The fix doesn't need a software update. It was just caused by changes of external data which is included in our feed and wasn't easy to fix.

**Closed** 2019-11-12 15:43 UTC

**Comment by blshkv** [comment] 2019-11-13 11:16
FYI, it took 3 hours for me. Is any better way of fixing it?
```
d manage:   INFO:2019-11-13 05h07.25 utc:530: Updating DFN-CERT CVSS max succeeded.                    
d manage:   INFO:2019-11-13 05h07.25 utc:530: Updating Max CVSS for CERT-Bund                          
d manage:   INFO:2019-11-13 05h07.25 utc:530: Updating CERT-Bund CVSS max succeeded.                   
d manage:   INFO:2019-11-13 05h07.25 utc:530: sync_cert: Updating CERT info succeeded.                 
d manage:   INFO:2019-11-13 05h07.33 utc:527: OSP service has newer VT status (version 201911121109) th
d manage:   INFO:2019-11-13 05h07.49 utc:527: Updating VTs in database ... 288 new VTs, 1340 changed VT
d manage:   INFO:2019-11-13 05h07.59 utc:527: Updating VTs in database ... done (53337 VTs).           
d manage:   INFO:2019-11-13 06h23.19 utc:526: Updating /var/lib/gvm/scap-data/nvdcve-2.0-2008.xml      
d manage:   INFO:2019-11-13 06h24.09 utc:526: Updating /var/lib/gvm/scap-data/nvdcve-2.0-2015.xml      
d manage:   INFO:2019-11-13 06h25.18 utc:526: Updating /var/lib/gvm/scap-data/nvdcve-2.0-2009.xml      
d manage:   INFO:2019-11-13 06h26.48 utc:526: Updating /var/lib/gvm/scap-data/nvdcve-2.0-2019.xml      
d manage:   INFO:2019-11-13 06h31.12 utc:526: Updating /var/lib/gvm/scap-data/nvdcve-2.0-2013.xml      
d manage:   INFO:2019-11-13 06h34.24 utc:526: Updating /var/lib/gvm/scap-data/nvdcve-2.0-2003.xml      
d manage:   INFO:2019-11-13 06h34.31 utc:526: Updating /var/lib/gvm/scap-data/nvdcve-2.0-2006.xml      
d manage:   INFO:2019-11-13 06h35.07 utc:526: Updating /var/lib/gvm/scap-data/nvdcve-2.0-2010.xml      
d manage:   INFO:2019-11-13 06h39.20 utc:526: Updating /var/lib/gvm/scap-data/nvdcve-2.0-2012.xml      
d manage:   INFO:2019-11-13 06h42.06 utc:526: Updating /var/lib/gvm/scap-data/nvdcve-2.0-2007.xml      
d manage:   INFO:2019-11-13 06h42.34 utc:526: Updating /var/lib/gvm/scap-data/nvdcve-2.0-2011.xml      
d manage:   INFO:2019-11-13 07h47.23 utc:526: Updating /var/lib/gvm/scap-data/nvdcve-2.0-2004.xml      
d manage:   INFO:2019-11-13 07h47.40 utc:526: Updating /var/lib/gvm/scap-data/nvdcve-2.0-2005.xml      
d manage:   INFO:2019-11-13 07h48.02 utc:526: Updating /var/lib/gvm/scap-data/nvdcve-2.0-2014.xml      
d manage:   INFO:2019-11-13 07h49.57 utc:526: Updating /var/lib/gvm/scap-data/nvdcve-2.0-2016.xml      
d manage:   INFO:2019-11-13 07h51.27 utc:526: Updating /var/lib/gvm/scap-data/nvdcve-2.0-2017.xml      
d manage:   INFO:2019-11-13 07h53.27 utc:526: Updating /var/lib/gvm/scap-data/nvdcve-2.0-2002.xml      
d manage:   INFO:2019-11-13 07h53.46 utc:526: Updating /var/lib/gvm/scap-data/nvdcve-2.0-2018.xml      
d manage:   INFO:2019-11-13 07h59.56 utc:526: Updating OVAL data 
```
