### ISSUE TITLE
The database was created using collation version 2.35, but the operating system provides version 2.36.

### ISSUE THREAD

**Issue by cqgc01** [greenbone/gvmd#1878] opened 2022-11-28 16:02 UTC
Hi all.

Nov 28 08:27:57  gvmd[17457]: HINT:  Rebuild all objects in this database that use the default collation and run ALTER DATABASE gvmd REFRESH COLLATION VERSION, or build PostgreSQL with the right library version.
Nov 28 08:27:57  gvmd[17461]: WARNING:  database "gvmd" has a collation version mismatch
Nov 28 08:27:57  gvmd[17461]: DETAIL:  The database was created using collation version 2.35, but the operating system provides version 2.36.
Nov 28 08:27:57  gvmd[17461]: HINT:  Rebuild all objects in this database that use the default collation and run ALTER DATABASE gvmd REFRESH COLLATION VERSION, or build PostgreSQL with the right library version.
Nov 28 08:27:57  gvmd[17462]: WARNING:  database "gvmd" has a collation version mismatch
Nov 28 08:27:57  gvmd[17462]: DETAIL:  The database was created using collation version 2.35, but the operating system provides version 2.36.
Nov 28 08:27:57  gvmd[17462]: HINT:  Rebuild all objects in this database that use the default collation and run ALTER DATABASE gvmd REFRESH COLLATION VERSION, or build PostgreSQL with the right library version.
Nov 28 08:27:57  gvmd[17465]: WARNING:  database "gvmd" has a collation version mismatch
Nov 28 08:27:57  gvmd[17465]: DETAIL:  The database was created using collation version 2.35, but the operating system provides version 2.36.
Nov 28 08:27:57  gvmd[17465]: HINT:  Rebuild all objects in this database that use the default collation and run ALTER DATABASE gvmd REFRESH COLLATION VERSION, or build PostgreSQL with the right library version.

I will appreciate a procedure to solve this issue.

**Comment by cfi-gb** [comment] 2023-01-30 07:50
@greenbone/gvmd-maintainers This could be closed as "invalid" and the "bug" label removed.

It seems it is a standard database maintenance / administration task and not a bug/issue in gvmd:

> Nov 28 08:27:57 gvmd[17462]: HINT: Rebuild all objects in this database that use the default collation and run ALTER DATABASE gvmd REFRESH COLLATION VERSION, or build PostgreSQL with the right library version.

The commands have been confirmed to work by a community user here:

https://forum.greenbone.net/t/the-database-was-created-using-collation-version-2-35-but-the-operating-system-provides-version-2-36/13562/4

Some more info about this is available from Debian side here:

> https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1029548#10
>
> The cause for that (IIUC) is that the database was created when libc6 was at version 2.35 and it has since been upgraded to 2.36.
>
> See also https://bugs.debian.org/1021074
>
> *snip*
>
> A (major) libc6 upgrade is not something that will happen on Stable, so this issue may only occur with people running Testing or Unstable.
> OTOH: There are now (at least) 2 people who ran into it and didn't know what to do with/about it.

**Closed** 2023-01-30 17:58 UTC
Labels: bug
